import type { Metadata } from "next";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "About",
  description:
    "How RepoRadar works: data sources, update cadence, star history methodology, jump detection, and how the AI-generated sections are produced and reviewed.",
  alternates: { canonical: "/about" },
};

export default function AboutPage() {
  return (
    <article className="prose mx-auto max-w-3xl" data-pagefind-body>
      <h1 className="text-2xl font-semibold tracking-tight">About {site.name}</h1>
      <p>
        {site.name} is an automated open-source intelligence site. Twice a day it collects the
        repositories trending on GitHub, records their star and fork counts, and publishes reports
        that stay online forever — so trends are visible over weeks and months, not just today.
      </p>
      <h2>Where the data comes from</h2>
      <ul>
        <li>Trending lists are read from GitHub&apos;s public trending pages (daily, weekly, monthly).</li>
        <li>
          Repository facts — stars, forks, watchers, license, languages, topics, contributors,
          branches, tags, first commit and commit counts — come from the GitHub REST and GraphQL
          APIs.
        </li>
        <li>
          Activity and insight graphs use GitHub&apos;s statistics endpoints: per-day commit counts
          for the contribution heatmap, weekly additions and deletions for code frequency, the
          punch card for weekday and hour patterns, and participation for the maintainer versus
          community split.
        </li>
        <li>
          READMEs are rendered by GitHub and embedded directly, so you can read a project without
          leaving the page. Releases, recent issues, discussions, pull requests, Actions results,
          and the dependency graph (SBOM) come from their respective endpoints.
        </li>
        <li>
          Star history before we started tracking is reconstructed from public GitHub event
          archives and calibrated to each repository&apos;s current star count; from then on our own
          twice-daily snapshots extend the curve. GitHub no longer exposes per-star timestamps
          directly.
        </li>
      </ul>
      <h2>Signals and awards</h2>
      <p>
        GitHub does not expose profile achievements or trophies through any public API, so the
        awards shown on repository pages are computed by us from the data above. Each one maps to a
        stated rule — for example, &quot;Breakout launch&quot; means at least 3,000 stars within 120
        days of creation, and &quot;Outside contributions&quot; means at least 70 percent of the last
        year&apos;s commits came from people other than the maintainer.
      </p>
      <h2>Jump detection</h2>
      <p>
        A star jump is flagged when a repository gains stars at more than three times its trailing
        seven-day daily average (with a minimum threshold to avoid noise). Jumps usually indicate a
        launch, a viral post, or a major release.
      </p>
      <h2>AI-generated sections</h2>
      <p>
        The &quot;what it does&quot;, &quot;use cases&quot;, and &quot;getting started&quot;
        sections are generated by a language model from each repository&apos;s README and metadata,
        then land in the site through reviewed pull requests. Everything else on a repository page
        is raw data from the GitHub API.
      </p>
      <h2>Update cadence</h2>
      <p>
        A morning run publishes the daily report and refreshes trending lists. An evening run
        refreshes star snapshots and detects jumps. Weekly digests are published on Sundays and
        monthly roundups on the first of each month.
      </p>
      <h2>Who built this</h2>
      <p>
        {site.name} is built and maintained by {site.creator.name}, a software engineer building
        small, focused products.{" "}
        <a href={site.creator.github} target="_blank" rel="noopener noreferrer">GitHub</a>
        {" · "}
        <a href={site.creator.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a>
        {" · "}
        <a href={site.creator.portfolio} target="_blank" rel="noopener noreferrer">Portfolio</a>
      </p>
    </article>
  );
}
