import type { Metadata } from "next";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "About",
  description:
    "How RepoRadar works: data sources, update cadence, star history methodology, jump detection, and how the AI-generated sections are produced and reviewed.",
  alternates: { canonical: "/about" },
};

export default function AboutPage() {
  return (
    <article className="prose mx-auto max-w-3xl" data-pagefind-body>
      <h1 className="text-2xl font-semibold tracking-tight">About {site.name}</h1>
      <p>
        {site.name} is an automated open-source intelligence site. Twice a day it collects the
        repositories trending on GitHub, records their star and fork counts, and publishes reports
        that stay online forever — so trends are visible over weeks and months, not just today.
      </p>
      <h2>Where the data comes from</h2>
      <ul>
        <li>Trending lists are read from GitHub&apos;s public trending pages (daily, weekly, monthly).</li>
        <li>
          Repository facts — stars, forks, license, languages, topics, contributors, first commit,
          commit counts — come from the official GitHub REST API.
        </li>
        <li>
          Star history is built from our own snapshots: each pipeline run records the current star
          count, so every tracked repository accumulates a genuine time series.
        </li>
      </ul>
      <h2>Jump detection</h2>
      <p>
        A star jump is flagged when a repository gains stars at more than three times its trailing
        seven-day daily average (with a minimum threshold to avoid noise). Jumps usually indicate a
        launch, a viral post, or a major release.
      </p>
      <h2>AI-generated sections</h2>
      <p>
        The &quot;what it does&quot;, &quot;use cases&quot;, and &quot;getting started&quot;
        sections are generated by a language model from each repository&apos;s README and metadata,
        then land in the site through reviewed pull requests. Everything else on a repository page
        is raw data from the GitHub API.
      </p>
      <h2>Update cadence</h2>
      <p>
        A morning run publishes the daily report and refreshes trending lists. An evening run
        refreshes star snapshots and detects jumps. Weekly digests are published on Sundays and
        monthly roundups on the first of each month.
      </p>
    </article>
  );
}
