import { marked } from "marked";

// Reports are generated by our own pipeline (and Jules PRs reviewed before
// merge), so the Markdown source is trusted. Rendered at build time only.
export function renderMarkdown(md: string): string {
  return marked.parse(md, { async: false }) as string;
}
